openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Rock paper scissors
paths:
  /v1/game:
    post:
      summary: start a new game
      operationId: StartNewGame
      responses:
        '201':
          description: game created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Game"
        '422':
          description: cannot create a game
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/game/{gameId}:
    get:
      summary: Game
      operationId: Game
      tags:
        - game
      parameters:
        - name: gameId
          in: path
          required: true
          description: The id of the game
          schema:
            type: integer
      responses:
        '200':
          description: Game
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Game"
        '404':
          description: A game with the specified ID was not found.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: send your game and current item IDs to server
      operationId: Play
      parameters:
        - name: gameId
          in: path
          required: true
          description: The id of the game
          schema:
            type: integer
      requestBody:
        description: item and player ID
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      tags:
        - play
      responses:
        '200':
          description: played succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        '404':
          description: Cannot accept such item for such game Id.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Game:
      type: object
      required:
        - gameid
        - status
      properties:
        gameid:
          type: integer
          format: int64
        status:
          type: string
          enum: [player_failed, server_failed, in_progress, not_identified]
          default: not_identified
    Item:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          enum: [rock, paper, scissors]
          default: rock
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string