spring:
  datasource:
    url: jdbc:h2:mem:rockpaperscissors
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.yaml